ProyectoWsicav/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoWsicav.Models;

namespace ProyectoWsicav.Controllers
{
    public class UsuariosController : Controller
    {
        UsersContext ctx;

        public UsuariosController(UsersContext _ctx)
        {
            ctx = _ctx;
        }

        public async Task<IActionResult> Index()
        {
            List<TblUsuario> Usuarios = await ctx.TblUsuario.Include("Permiso").ToListAsync();
            //List<TblUsuario> Usuarios = await ctx.TblUsuario.ToListAsync();
            TblUsuario Usua = new TblUsuario();
            ViewBag.Usuario = Usuarios;

            ViewBag.TblPermiso = await ctx.TblPermiso.OrderBy(x => x.Descripcion).ToListAsync();
            ViewData["Permisos"] = new SelectList(ctx.TblPermiso, "Id", "PermisoId");

            return View(Usua);
        }

        [BindProperty]
        public TblUsuario Usuari { get; set; }
        public async Task<IActionResult> GuardarUsuario()
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            var _Usuari = await ctx.TblUsuario.Where(x => x.Id == Usuari.Id).AnyAsync();

            if (!_Usuari)
            {
                ctx.TblUsuario.Add(Usuari);
            }
            else
            {
                ctx.TblUsuario.Attach(Usuari);
                ctx.Entry(Usuari).State = EntityState.Modified;
            }

            await ctx.SaveChangesAsync();
            return RedirectToAction("Index");

        }

        public async Task<IActionResult> Modificar(int id)
        {
            var Usuari = await ctx.TblUsuario.FindAsync(id);

            if (Usuari == null)
            {
                return RedirectToAction("Index");
            }


            ViewBag.TblPermiso = await ctx.TblPermiso.OrderBy(x => x.Descripcion).ToListAsync();

            ViewBag.Usuario = await ctx.TblUsuario.Include("Permiso").ToListAsync();
            //ViewBag.Usuario = await ctx.TblUsuario.ToListAsync();


            return View(Usuari);

        }

        public async Task<IActionResult> Eliminar(int id)
        {
            var _Usuari = await ctx.TblUsuario.FindAsync(id);

            if (_Usuari == null)
            {
                return RedirectToAction("Index");

            }
            else
            {
                ctx.TblUsuario.Remove(_Usuari);
                ctx.SaveChanges();
                return RedirectToAction("Index");
            }
        }
    }
}

ProyectoWsicav/Views/Usuarios/Index.cshtml


<partial name="~/Views/Usuarios/_Form.cshtml">

    <partial name="~/Views/Usuarios/_Listado.cshtml">

ProyectoWsicav/Views/Usuarios/Modificar.cshtml

    <partial name="~/Views/Usuarios/_Form.cshtml">

        <partial name="~/Views/Usuarios/_Listado.cshtml">



ProyectoWsicav/Views/Usuarios/_Form.cshtml

@model TblUsuario

<br />
<div class="col-md-12">
    <div class="box box-warning">
        <div class="box-header with-border">
            <h3 class="box-title" style="font-weight:bold;">Registro de Usuarios</h3>
            <form asp-action="GuardarUsuario" asp-controller="Usuarios" method="post">
                <br />
                <input type="hidden" asp-for="Id" />
                <div class="form-row">
                    <div class="form-group col-md-3">
                        <label for="inputEmail4">Apellidos</label>
                        <input type="text" class="form-control" asp-for="Apellido" placeholder="Ingrese Nombres">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="inputEmail4">Nombres</label>
                        <input type="text" class="form-control" asp-for="Nombre" placeholder="Ingrese Nombres">
                    </div>
                    <div class="form-group col-md-2">
                        <label for="inputPassword4">Password</label>
                        <input type="password" class="form-control" asp-for="Password" placeholder="Ingrese Telefono">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="inputPassword4">Email</label>
                        <input type="text" class="form-control" asp-for="Email" placeholder="Ingrese Celular">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="inputEmail4">Usuario</label>
                        <input type="text" class="form-control" asp-for="Usuario" placeholder="Ingrese Nombres">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="inputEmail4">Departamento</label>
                        <input type="text" class="form-control" asp-for="CodigoDepartamento" placeholder="Ingrese Nombres">
                    </div>
                    <div class="form-group col-md-2">
                        <label>Permiso(*)</label>
                        <div class="form-row">
                            <select asp-items="ViewBag.Permisos" name="PermisoId" class="form-control" style="width: 100%;" data-select2-id="1" tabindex="-1" aria-hidden="true">
                                <option selected="selected" data-select2-id="3">Seleccionar ...</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-1">
                    <label for="inputAddress"></label>
                    <br />
                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Registrar</button>
                </div>
            </form>

        </div>
    </div>
</div>

ProyectoWsicav/Views/Usuarios/_Listado.cshtml
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-success">
                <div class="box-header">
                    <h3 class="box-title" style="font-weight:bold;">Listado de Usuario</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="tablaCliente" class="table table-bordered table-striped dt-responsive tablas">
                        <thead>
                            <tr>
                                <th>Nombres</th>
                                <th>Apellidos</th>
                                <th>Password</th>
                                <th>Email</th>
                                <th>Usuario</th>
                                <th>Departamento</th>
                                <th>Rol</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (TblUsuario Usua in ViewBag.Usuario)
                            {

                                <tr>
                                    <td>@Usua.Nombre</td>
                                    <td>@Usua.Apellido</td>
                                    <td>@Usua.Password</td>
                                    <td>@Usua.Email</td>
                                    <td>@Usua.Usuario</td>
                                    <td>@Usua.CodigoDepartamento</td>
                                    <td>@Usua.Permiso.Descripcion</td>
                                    <td>
                                        <div class="btn-group">
                                            <a asp-action="Modificar" asp-controller="Usuarios" asp-route-id="@Usua.Id" class="btn btn-block btn-warning btn-xs"><i class="fa fa-refresh"></i></a>
                                        </div>
                                        <div class="btn-group">
                                            <a asp-action="Eliminar" onclick="return confirm('¿Desea eliminar este registro?')" asp-controller="Usuarios" asp-route-id="@Usua.Id" class="btn btn-block btn-danger btn-xs btnEliminar"><i class="fa fa-ban"></i></a>
                                        </div>
                                    </td>
                                </tr>

                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->