ProyectoWsicav/Controllers/AccesoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProyectoWsicav.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace ProyectoWsicav.Controllers
{
    public class AccesoController : Controller
    {
        UsersContext uct = new UsersContext();
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ValidarAcceso(TblUsuario user)
        {
            var _usuario = uct.TblUsuario.Where(x => x.Usuario == user.Usuario);
            if (_usuario.Any())
            {
                if (_usuario.Where(x => x.Password == user.Password).Any())
                {
                    if (HttpContext.Session.GetString("NombreUser") == null)
                    {
                        TblUsuario _nomuser = new TblUsuario();
                        _nomuser = (TblUsuario)uct.TblUsuario.Where(x => x.Usuario == user.Usuario).FirstOrDefault();
                        string nombrecompleto = _nomuser.Nombre.ToString() + " " + _nomuser.Apellido.ToString();
                //        string stato = _nomuser.Supervisor.ToString();
                        string usuar = _nomuser.Usuario.ToString();
                        HttpContext.Session.SetObjectAsJson("Usuario", _nomuser);
                        //HttpContext.Session.SetString("NombreUser", nombrecompleto);
                        //HttpContext.Session.SetString("stato", stato);
                        //HttpContext.Session.SetString("User", usuar);
                    }
                    TblUsuario nom = HttpContext.Session.GetObjectFromJson<TblUsuario>("Usuario");
                    string nomCom = nom.Nombre.ToString() + " " + nom.Apellido.ToString();
                    return Json(new { status = true, message = nomCom });
                }
                else
                {
                    return Json(new { status = false, message = "Contraseña Incorrecta" });
                }
            }
            else
            {
                return Json(new { status = false, message = "Usuario Incorrecto" });
            }
        }
        public void linnq(TblUsuario user)
        {
            var _usuario = uct.TblUsuario.Where(x => x.Usuario == user.Usuario);
            TblUsuario _nomuser = new TblUsuario();
            _nomuser = (TblUsuario)uct.TblUsuario.Where(x => x.Usuario == user.Usuario).FirstOrDefault();
            string nombrecompleto = _nomuser.Nombre.ToString() + " " + _nomuser.Apellido.ToString();
           // string stato = _nomuser.Supervisor.ToString();
            HttpContext.Session.SetString("NombreUser", nombrecompleto);
          //  HttpContext.Session.SetString("stato", stato);
        }

        [HttpGet]
        public IActionResult _MostrarUsuario()
        {
            //ViewBag.Huesped = HttpContext.Session.GetObjectFromJson<TblUsuario>("Huesped");
            //var humm = ViewBag.Huesped;
            //var eldd = ViewBag.Huesped;
            string usuario = HttpContext.Session.GetString("Usuario");
            TblUsuario _nomuser = new TblUsuario();
            _nomuser = (TblUsuario)uct.TblUsuario.Where(x => x.Usuario == usuario).FirstOrDefault();
            ViewBag.Huesped = HttpContext.Session.GetString("NombreUser");
            ViewBag.statu = HttpContext.Session.GetString("stato");
            return PartialView(_nomuser);
        }
    }
}

ProyectoWsicav/Views/Acceso/Login.cshtml
@model TblUsuario
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/css/Lsite.css" />
    <title>Login-Wsicav</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" crossorigin="anonymous">
</head>
<body>
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="user_card">
                <div class="d-flex justify-content-center">
                    <div class="brand_logo_container">
                        <img src="~/images/LogoWsicav.png" class="brand_logo" alt="Logo">
                    </div>
                </div>
                <div class="d-flex justify-content-center form_container">
                    <form>
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input type="text" name="Usuario" id="Usuario" class="form-control input_user" value="" placeholder="Usuario">
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            <input type="password" name="password" id="password" class="form-control input_pass" value="" onkeypress="return runScript(event)" placeholder="Contraseña">
                        </div>
                        @*<div class="form-group">
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" id="customControlInline">
                                    <label class="custom-control-label" for="customControlInline">Remember me</label>
                                </div>
                            </div>*@
                        <div class="d-flex justify-content-center mt-3 login_container">
                            <button type="button" value="Login" name="button" class="btn login_btn" onkeypress="return runScript(event)">Login</button>
                        </div>
                    </form>
                    @*</div>
                        <div class="mt-4">
                            <div class="d-flex justify-content-center links">
                                Don't have an account? <a href="#" class="ml-2">Sign Up</a>
                            </div>
                            <div class="d-flex justify-content-center links">
                                <a href="#">Forgot your password?</a>
                            </div>
                        </div>*@
                </div>
            </div>
        </div>
</body>
</html>
<script>

    function runScript(e) {
      if (e.keyCode == 13) {

          Validate();

          return false;
      }
  }

    function MostrarBienvenida(result)
    {
        Swal.fire({
            icon: 'success',
            imageUrl:'/images/LogoWsicav.png',
              title: 'Bienvenido',
            text: result.message
        })
    };
    function AbrirPagina()
    {
                window.location.href = '@Url.Action("Inicio", "Solicitudes")';
    };
    function Validate() {
        $.ajax(
        {
          type: "POST",
          url: '@Url.Action("ValidarAcceso", "Acceso")',
          data: {
            Usuario: $('#Usuario').val(),
            password: $('#password').val()
          },
          error: function (result) {
            Swal.fire({
              icon: 'error',
              title: 'Oops...',
              text: 'Contacte con su Proveedor'
            })
          },
          success: function (result) {
            console.log(result);
              if (result.status == true) {
                  window.onload = MostrarBienvenida(result)
                  event.preventDefault(); //esto cancela el comportamiento del click
                  setTimeout(()=> location.href='@Url.Action("Inicio", "Solicitudes")',2000);
            }
            else {
              Swal.fire({
              icon: 'error',
              title: 'Oops...',
              text: result.message,
              footer: '<a href>Los nombres de usuario y clave son unicos</a>'
            })
            }
          }
        });
    }
</script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>