ProyectoWsicav/Controllers/DestinosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoWsicav.Models;
using System.Web;
using System.Text;
using Newtonsoft.Json.Linq;
using ProyectoWsicav.ViewModel;
using Hangfire;
using ProyectoWsicav.Demo;

namespace ProyectoWsicav.Controllers
{
    public class DestinosController : Controller
    {
        private readonly UsersContext _context;

        private IDemoService demoService;
        //private CorreoCampanaController obj;

        // GET: HangFire

        public DestinosController(UsersContext context)
        {
            _context = context;
        }
       
        public ActionResult Test()
        {

            // BackgroundJob.Enqueue(() => demoService.RunTask());
            RecurringJob.AddOrUpdate(() => demoService.RunTask(), Cron.Minutely);
            return Json(0);
        }
      

        // GET: Destinos
        public async Task<IActionResult> Index()
        {
          
            List<VmDestino> list = new List<VmDestino>();
            var v = (from a in _context.TblDestino
                     join b in _context.TblCiudad on a.CiudadId equals b.Id
                     select new VmDestino
                     {
                         Id = a.Id,
                         Nombre = a.Nombre,
                         CiudadId = a.CiudadId,
                         NombreCiudad = b.NombreCiudad
                     });
            list = await v.ToListAsync();
            return View(list);
        }
        [HttpPost]
        public ActionResult saveuser(int id, string propertyName, string value)
        {
            var status = false;
            var message = "";

            //Update data to database 

            var user = _context.TblDestino.Find(id);

            object updateValue = value;
            bool isValid = true;

            if (propertyName == "CiudadId")
            {
                int newRoleID = 0;
                if (int.TryParse(value, out newRoleID))
                {
                    updateValue = newRoleID;
                    //Update value field
                    value = _context.TblCiudad.Where(a => a.Id == newRoleID).First().NombreCiudad;
                }
                else
                {
                    isValid = false;
                }

            }
            //else if (propertyName == "DOB")
            //{
            //    DateTime dob;
            //    if (DateTime.TryParseExact(value, "dd-MM-yyyy", new CultureInfo("en-US"), DateTimeStyles.None, out dob))
            //    {
            //        updateValue = dob;
            //    }
            //    else
            //    {
            //        isValid = false;
            //    }
            //}

            if (user != null && isValid)
            {
                _context.Entry(user).Property(propertyName).CurrentValue = updateValue;
                _context.SaveChanges();
                status = true;
            }
            else
            {
                message = "Error!";
            }


            var response = new { value = value, status = status, message = message };
            JObject o = JObject.FromObject(response);
            return Content(o.ToString());
        }

        public ActionResult GetUserRoles(int id)
        {
            //{'E':'Letter E','F':'Letter F','G':'Letter G', 'selected':'F'}
            int selectedRoleID = 0;
            StringBuilder sb = new StringBuilder();

            var roles = _context.TblCiudad.OrderBy(a => a.NombreCiudad).ToList();
            foreach (var item in roles)
            {
                sb.Append(string.Format("'{0}':'{1}',", item.Id, item.NombreCiudad));
            }

            selectedRoleID = _context.TblCiudad.Where(a => a.Id == id).First().Id;



            sb.Append(string.Format("'selected': '{0}'", selectedRoleID));
            return Content("{" + sb.ToString() + "}");
        }


        // GET: Destinos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblDestino = await _context.TblDestino
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tblDestino == null)
            {
                return NotFound();
            }

            return View(tblDestino);
        }

        // GET: Destinos/Create
        public IActionResult Create()
        {
            ViewData["CiudadId"] = new SelectList(_context.TblCiudad, "Id", "Id");
            return View();
        }

        // POST: Destinos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CiudadId,Nombre")] TblDestino tblDestino)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tblDestino);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CiudadId"] = new SelectList(_context.TblCiudad, "Id", "Id", tblDestino.CiudadId);
            return View(tblDestino);
        }

        // GET: Destinos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblDestino = await _context.TblDestino.FindAsync(id);
            if (tblDestino == null)
            {
                return NotFound();
            }
            ViewData["CiudadId"] = new SelectList(_context.TblCiudad, "Id", "Id", tblDestino.CiudadId);
            return View(tblDestino);
        }

        // POST: Destinos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CiudadId,Nombre")] TblDestino tblDestino)
        {
            if (id != tblDestino.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tblDestino);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TblDestinoExists(tblDestino.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CiudadId"] = new SelectList(_context.TblCiudad, "Id", "Id", tblDestino.CiudadId);
            return View(tblDestino);
        }

        // GET: Destinos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblDestino = await _context.TblDestino
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tblDestino == null)
            {
                return NotFound();
            }

            return View(tblDestino);
        }

        // POST: Destinos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tblDestino = await _context.TblDestino.FindAsync(id);
            _context.TblDestino.Remove(tblDestino);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TblDestinoExists(int id)
        {
            return _context.TblDestino.Any(e => e.Id == id);
        }
    }
}

ProyectoWsicav/Views/Destinos/Index.cshtml
@model IEnumerable<ProyectoWsicav.ViewModel.VmDestino>

@{
    ViewBag.Title = "Index";
    //WebGrid grid = new WebGrid(Model, rowsPerPage: 10);
}
<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreCiudad)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <div class="edit" data-id="@item.Id" data-propertyname="Nombre">  @Html.DisplayFor(modelItem => item.Nombre)</div>
                </td>
                <td>
                    <div class="editSelect" data-id="@item.Id" data-propertynameid=@item.CiudadId data-propertyname="CiudadId">    @Html.DisplayFor(modelItem => item.NombreCiudad)</div>
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@*<div class="row">
        @grid.GetHtml(
            tableStyle: "table table-responsive table-striped table-bordered",
            columns: grid.Columns(
                grid.Column(header: "First Name", format: @<text><div class="edit" data-id="@item.ID" data-propertyname="FirstName">@item.FirstName</div></text>),
    grid.Column(header: "Last Name", format:@<text><div class="edit" data-id="@item.ID" data-propertyname="LastName">@item.LastName</div></text>),
    grid.Column(header: "Role", format:@<text><div class="editSelect" data-id="@item.ID" data-propertyname="RoleID">@item.RoleName</div></text>),
    grid.Column(header: "DOB", format:@<text><div class="editDate" data-id="@item.ID" data-propertyname="DOB">@string.Format("{0:dd-MM-yyyy}", item.DOB)</div></text>)
    )
    )
    </div>*@

<link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" rel="stylesheet" />


<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

<script src="https://www.appelsiini.net/download/jquery.jeditable.js"></script>
<script src="~/Scripts/jquery.jeditable.datepicker.js"></script>
<script>
        $(document).ready(function () {
            var oldValue = '';
            $('.edit').editable('/Destinos/saveuser', {
                cssclass: 'jeditForm',
                tooltip: 'click to edit me...',
                width: 'none',
                height: 'none',
                onsubmit: function (settings, original) {
                    oldValue = original.revert;
                },
                submitdata: function () {
                    return {
                        id: $(this).data('id'),
                        PropertyName: $(this).data('propertyname')
                    }
                },
                callback: function (value, settings) {
                    var jsonData = $.parseJSON(value);
                    if (jsonData.status) {
                        $(this).text(jsonData.value);
                    }
                    else {
                        $(this).text(oldValue);
                    }
                }
            })

            $('.editSelect').editable('/Destinos/saveuser', {
                cssclass: 'jeditForm',
                tooltip: 'click to edit me...',
                width: 'none',
                height: 'none',
                type: 'select',
                submit: 'Ok',
                loadurl: '/Destinos/GetUserRoles',
                loaddata: function () {
                    return {id: $(this).data('propertynameid')}
                },
                onsubmit: function (settings, original) {
                    oldValue = original.revert;
                },
                submitdata: function () {
                    return {
                        id: $(this).data('id'),
                        PropertyName: $(this).data('propertyname')
                    }
                },
                callback: function (value, settings) {
                    var jsonData = $.parseJSON(value);
                    if (jsonData.status) {
                        $(this).text(jsonData.value);
                    }
                    else {
                        $(this).text(oldValue);
                    }
                }
            })

            $('.editSelect').click(function () {
                $('select', this).addClass('form-control pull-left w100');
                $('button', this).addClass('btn btn-sm btn-success margin10')
            })

            $('.editDate').editable('/Destinos/saveuser', {
                cssclass: 'jeditForm',
                tooltip: 'click to edit me...',
                type: 'datepicker',
                datepicker: {
                    dateFormat: 'dd-mm-yy',
                    changeMonth: true,
                    changeYear: true,
                    yearRange: '1900:' +(new Date().getFullYear()  - 18)
                },
                onsubmit: function (settings, original) {
                    oldValue = original.revert;
                },
                submitdata: function () {
                    return {
                        id: $(this).data('id'),
                        PropertyName: $(this).data('propertyname')
                    }
                },
                callback: function (value, settings) {
                    var jsonData = $.parseJSON(value);
                    if (jsonData.status) {
                        $(this).text(jsonData.value);
                    }
                    else {
                        $(this).text(oldValue);
                    }
                }
            })
        })
</script>

ProyectoWsicav/Views/Destinos/Modificar.cshtml

<partial name="~/Views/Destinos/_Form.cshtml">

<partial name="~/Views/Destinos/_Listado.cshtml">



ProyectoWsicav/Views/Destinos/_Form.cshtml

@model TblDestino

<br />
<div class="col-md-12">
    <div class="box box-warning">
        <div class="box-header with-border">
            <h3 class="box-title" style="font-weight:bold;">Registro de Destinos</h3>
            <form asp-action="GuardarDestino" asp-controller="Destinos" method="post">
                <br />
                <input type="hidden" asp-for="Id" />
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="inputAddress">Destino</label>
                        <input type="text" class="form-control" asp-for="Nombre" placeholder="Destino">
                    </div>
                    <div class="form-group col-md-2">
                        <label>Ciudades(*)</label>
                        <select asp-for="CiudadId" class="form-control" asp-items="@(new SelectList(ViewBag.TblCiudad, "Id", "NombreCiudad"))">
                            <option>Seleccione</option>
                        </select>
                    </div>
                </div>
                <div class="form-group col-md-1">
                    <label for="inputAddress"></label>
                    <br />
                    <button class="btn btn-primary"><i class="fa fa-save"></i> Registrar</button>
                </div>
            </form>

        </div>
    </div>
</div>

ProyectoWsicav/Views/Destinos/_Listado.cshtml
<section class="content">
<div class="row">
    <div class="col-xs-12">
        <div class="box box-success">
            <div class="box-header">
                <h3 class="box-title" style="font-weight:bold;">Listado de Ciudades</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="tablaCliente" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Destino</th>
                            <th>Ciudad</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (TblDestino Des in ViewBag.Destino)
                        {

                        <tr>
                            <td>@Des.Nombre</td>
                            <td>@Des.Ciudad.NombreCiudad</td>
                            <td>
                                <div class="btn-group">
                                    <a asp-action="Modificar" asp-controller="Destinos" asp-route-id="@Des.Id" class="btn btn-block btn-warning btn-xs"><i class="fa fa-refresh"></i></a>
                                </div>
                                <div class="btn-group">
                                    <a asp-action="Eliminar" onclick="return confirm('¿Desea eliminar este registro?')" asp-controller="Destinos" asp-route-id="@Des.Id" class="btn btn-block btn-danger btn-xs btnEliminar"><i class="fa fa-ban"></i></a>
                                </div>
                            </td>
                        </tr>

                        }
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
</section>
<!-- /.content -->