ProyectoWsicav/Controllers/GuiasController.cs
using System;

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProyectoWsicav.Models;

namespace ProyectoWsicav.Controllers
{
    public class GuiasController : Controller
    {
        UsersContext ctx;

        public GuiasController(UsersContext _ctx)
        {
            ctx = _ctx;
        }

        public async Task<IActionResult> Index()
        {
            List<TblGuia> Guias = await ctx.TblGuia.Include("TipoDocumentoIdentidad").ToListAsync();
            TblGuia Gui = new TblGuia();
            ViewBag.Guia = Guias;
            ViewBag.TblTipoDocumentoIdentidad = await ctx.TblTipoDocumentoIdentidad.OrderBy(x => x.Descripcion).ToListAsync();

            return View(Gui);
        }

        [BindProperty]
        public TblGuia Guia { get; set; }
        public async Task<IActionResult> GuardarGuia()
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            var _Guia = await ctx.TblGuia.Where(x => x.Id == Guia.Id).AnyAsync();

            if (!_Guia)
            {
                ctx.TblGuia.Add(Guia);
            }
            else
            {
                ctx.TblGuia.Attach(Guia);
                ctx.Entry(Guia).State = EntityState.Modified;
            }

            await ctx.SaveChangesAsync();
            return RedirectToAction("Index");

        }

        public async Task<IActionResult> Modificar(int id)
        {
            var Guia = await ctx.TblGuia.FindAsync(id);

            if (Guia == null)
            {
                return RedirectToAction("Index");
            }


            ViewBag.TblTipoDocumentoIdentidad = await ctx.TblTipoDocumentoIdentidad.OrderBy(x => x.Descripcion).ToListAsync();

            ViewBag.Guia = await ctx.TblGuia.Include("TipoDocumentoIdentidad").ToListAsync();


            return View(Guia);

        }

        public async Task<IActionResult> Eliminar(int id)
        {
            var _Guia = await ctx.TblGuia.FindAsync(id);

            if (_Guia == null)
            {
                return RedirectToAction("Index");

            }
            else
            {
                ctx.TblGuia.Remove(_Guia);
                ctx.SaveChanges();
                return RedirectToAction("Index");
            }
        }

    }
}

ProyectoWsicav/Views/Guias/Index.cshtml
<partial name="~/Views/Guias/_Form.cshtml">

<partial name="~/Views/Guias/_Listado.cshtml">

ProyectoWsicav/Views/Guias/Inicio.cshtml
<br />
<div class="col-md-12">
    <div class="box box-warning">
        <div class="box-header with-border">
            <h3 class="box-title" style="font-weight:bold;">Registro de Guias</h3>
            <form>
                <br />
                <div class="form-row">
                    <div class="form-group col-md-2">
                        <label for="inputEmail4">Codigo</label>
                        <input type="text" class="form-control" id="inputEmail4" placeholder="Ingrese Codigo">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="inputPassword4">Fecha Ingreso</label>
                        <div class="input-group date">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" class="form-control pull-right" id="datepicker4" readonly value="12/02/2020">
                        </div>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="inputEmail4">Usuario</label>
                        <input type="text" class="form-control" id="inputEmail4" readonly value="Administrador">
                    </div>
                    <div class="form-group col-md-2">
                        <label for="inputEmail4">Tipo de Documento</label>
                        <select id="inputState" class="form-control">
                            <option selected>Seleccionar</option>
                            <option>DNI</option>
                            <option>RUC</option>
                            <option>CE</option>
                            <option>OTRO</option>
                        </select>
                    </div>
                    <div class="form-group col-md-2">
                        <label for="inputAddress">N° de Documento</label>
                        <input type="text" class="form-control" id="inputAddress" placeholder="Num Documento">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="inputEmail4">Apellidos</label>
                        <input type="email" class="form-control" id="inputEmail4" placeholder="Ingrese Nombres">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="inputEmail4">Nombres</label>
                        <input type="email" class="form-control" id="inputEmail4" placeholder="Ingrese Nombres">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="inputPassword4">Direccion</label>
                        <input type="password" class="form-control" id="inputPassword4" placeholder="Ingrese Direccion">
                    </div>
                    <div class="form-group col-md-2">
                        <label for="inputEmail4">Fecha de Nacimiento</label>
                        <div class="input-group date">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" class="form-control pull-right" id="datepicker2" placeholder="Fecha">
                        </div>
                    </div>
                    <div class="form-group col-md-1">
                        <label for="inputAddress">Edad</label>
                        <input type="text" class="form-control" placeholder="Edad">
                    </div>
                    <div class="form-group col-md-2">
                        <label for="inputPassword4">Telefono</label>
                        <input type="text" class="form-control" id="inputPassword4" placeholder="Ingrese Telefono">
                    </div>
                    <div class="form-group col-md-2">
                        <label for="inputPassword4">Email</label>
                        <input type="text" class="form-control" id="inputPassword4" placeholder="Ingrese Celular">
                    </div>
                    <div class="form-group col-md-2">
                        <label for="inputEmail4">Idiomas</label>
                        <select id="inputState" class="form-control">
                            <option selected>Seleccionar</option>
                            <option>Ingles</option>
                            <option>Aleman</option>
                            <option>Frances</option>
                            <option>Chino</option>
                        </select>
                    </div>
                    <div class="form-group col-md-2">
                        <label for="inputEmail4">Rutas/Excursiones</label>
                        <select id="inputState" class="form-control">
                            <option selected>Seleccionar</option>
                            <option>Lineas de Nazca</option>
                            <option>Ruta del Pisco</option>
                            <option>Ruta Ica</option>
                            <option>Ruta Pisco</option>
                        </select>
                    </div>
                    <div class="form-group col-md-2">
                        <label for="inputAddress">Contratado</label>
                        <br />
                        <input type="checkbox" class="minimal" checked>
                    </div>
                </div>
                <div class="form-group col-md-1">
                    <label for="inputAddress"></label>
                    <br />
                    <button class="btn btn-primary"><i class="fa fa-save"></i> Registrar</button>
                </div>
            </form>

        </div>
    </div>
</div>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-success">
                <div class="box-header">
                    <h3 class="box-title" style="font-weight:bold;">Listado de Guias</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="tablaCliente" class="table table-bordered table-striped dt-responsive tablas">
                        <thead>
                            <tr>
                                <th>Codigo</th>
                                <th>Fecha</th>
                                <th>Usuario</th>
                                <th>Tipo Documento</th>
                                <th>N° Documento</th>
                                <th>Nombres</th>
                                <th>Edad</th>
                                <th>Telefono</th>
                                <th>Email</th>
                                <th>Idiomas</th>
                                <th>Rutas</th>
                                <th>Contratado</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>G-21</td>
                                <td>12/02/2020</td>
                                <td>Administrador</td>
                                <td>DNI</td>
                                <td>45636908</td>
                                <td>Marco Jesus</td>
                                <td>42</td>
                                <td>953375829</td>
                                <td>marcoje_32@gmail.com</td>
                                <td>Ingles</td>
                                <td>Lineas de Nazca</td>
                                <td>Contratado</td>
                                <td>
                                    <div class="btn-group">
                                        <a href="#" class="btn btn-block btn-warning btn-xs"><i class="fa fa-refresh"></i></a>
                                    </div>
                                    <div class="btn-group">
                                        <a href="#" class="btn btn-block btn-danger btn-xs"><i class="fa fa-ban"></i></a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>G-21</td>
                                <td>12/02/2020</td>
                                <td>Administrador</td>
                                <td>DNI</td>
                                <td>45636908</td>
                                <td>Marco Jesus</td>
                                <td>42</td>
                                <td>953375829</td>
                                <td>marcoje_32@gmail.com</td>
                                <td>Ingles</td>
                                <td>Lineas de Nazca</td>
                                <td>Contratado</td>
                                <td>
                                    <div class="btn-group">
                                        <a href="#" class="btn btn-block btn-warning btn-xs"><i class="fa fa-refresh"></i></a>
                                    </div>
                                    <div class="btn-group">
                                        <a href="#" class="btn btn-block btn-danger btn-xs"><i class="fa fa-ban"></i></a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>G-21</td>
                                <td>12/02/2020</td>
                                <td>Administrador</td>
                                <td>DNI</td>
                                <td>45636908</td>
                                <td>Marco Jesus</td>
                                <td>42</td>
                                <td>953375829</td>
                                <td>marcoje_32@gmail.com</td>
                                <td>Ingles</td>
                                <td>Lineas de Nazca</td>
                                <td>Contratado</td>
                                <td>
                                    <div class="btn-group">
                                        <a href="#" class="btn btn-block btn-warning btn-xs"><i class="fa fa-refresh"></i></a>
                                    </div>
                                    <div class="btn-group">
                                        <a href="#" class="btn btn-block btn-danger btn-xs"><i class="fa fa-ban"></i></a>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->

<script>
        $(document).ready(function () {
            $(".tablas").DataTable({
                "language": {
                    "decimal": "",
                    "emptyTable": "No hay información",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ Registros",
                    "infoEmpty": "Mostrando 0 to 0 of 0 Registros",
                    "infoFiltered": "(Filtrado de _MAX_ total Registros)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ Registros",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "Sin resultados encontrados",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                },
                pageLength: 5,
                lengthMenu: [
                    [5, 10, 20, -1],
                    [5, 10, 20, 'Todos']
                ]
            });
        });
</script>

ProyectoWsicav/Views/Guias/Modificar.cshtml
<partial name="~/Views/Guias/_Form.cshtml">

    <partial name="~/Views/Guias/_Listado.cshtml">

ProyectoWsicav/Views/Guias/_Form.cshtml

@model  TblGuia

<br />
<div class="col-md-12">
    <div class="box box-warning">
        <div class="box-header with-border">
            <h3 class="box-title" style="font-weight:bold;">Registro de Guias</h3>
            <form asp-action="GuardarGuia" asp-controller="Guias" method="post">
                <br />
                <input type="hidden" asp-for="Id" />
                <div class="form-row">
                    <div class="form-group col-md-2">
                        <label for="inputEmail4">Codigo</label>
                        <input type="text" class="form-control" asp-for="Codigo" placeholder="Ingrese Codigo">
                    </div>
                    <div class="form-group col-md-2">
                        <label>Tipo de Documento(*)</label>
                        <select asp-for="TipoDocumentoIdentidadId" class="form-control" asp-items="@(new SelectList(ViewBag.TblTipoDocumentoIdentidad, "Id", "Descripcion"))">
                            <option>Seleccione</option>
                        </select>
                    </div>
                    <div class="form-group col-md-2">
                        <label for="inputAddress">N° de Documento</label>
                        <input type="text" class="form-control" asp-for="NumDocumento" placeholder="Num Documento">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="inputEmail4">Apellidos</label>
                        <input type="text" class="form-control" asp-for="Apellidos" placeholder="Ingrese Nombres">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="inputEmail4">Nombres</label>
                        <input type="text" class="form-control" asp-for="Nombres" placeholder="Ingrese Nombres">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="inputPassword4">Direccion</label>
                        <input type="text" class="form-control" asp-for="Direccion" placeholder="Ingrese Direccion">
                    </div>
                    <div class="form-group col-md-2">
                        <label for="inputPassword4">Telefono</label>
                        <input type="text" class="form-control" asp-for="Telefono" placeholder="Ingrese Telefono">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="inputPassword4">Email</label>
                        <input type="text" class="form-control" asp-for="Email" placeholder="Ingrese Celular">
                    </div>
                </div>
                <div class="form-group col-md-1">
                    <label for="inputAddress"></label>
                    <br />
                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Registrar</button>
                </div>
            </form>

        </div>
    </div>
</div>

ProyectoWsicav/Views/Guias/_Listado.cshtml

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-success">
                <div class="box-header">
                    <h3 class="box-title" style="font-weight:bold;">Listado de Guias</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="tablaCliente" class="table table-bordered table-striped dt-responsive tablas">
                        <thead>
                            <tr>
                                <th>Codigo</th>
                                <th>Tipo Documento</th>
                                <th>N° Documento</th>
                                <th>Apellidos</th>
                                <th>Nombres</th>
                                <th>Direccion</th>
                                <th>Telefono</th>
                                <th>Email</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (TblGuia Gui in ViewBag.Guia)
                            {

                                <tr>
                                    <td>@Gui.Codigo</td>
                                    <td>@Gui.TipoDocumentoIdentidad.Descripcion</td>
                                    <td>@Gui.NumDocumento</td>
                                    <td>@Gui.Apellidos</td>
                                    <td>@Gui.Nombres</td>
                                    <td>@Gui.Direccion</td>
                                    <td>@Gui.Telefono</td>
                                    <td>@Gui.Email</td>
                                    <td>
                                        <div class="btn-group">
                                            <a asp-action="Modificar" asp-controller="Guias" asp-route-id="@Gui.Id" class="btn btn-block btn-warning btn-xs"><i class="fa fa-refresh"></i></a>
                                        </div>
                                        <div class="btn-group">
                                            <a asp-action="Eliminar" onclick="return confirm('¿Desea eliminar este registro?')" asp-controller="Guias" asp-route-id="@Gui.Id" class="btn btn-block btn-danger btn-xs btnEliminar"><i class="fa fa-ban"></i></a>
                                        </div>
                                    </td>
                                </tr>

                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->